### PR TITLE
Fix Cargo.lock dependency

### PR DESCRIPTION
**Pull request by snorrees**
box-format renamed master branch to main.

This should fix the build.

### CODE REVIEW

**Comment by bbqsrc** [comment]
Danke!

**Comment by snorrees** [comment]
This has to be some kind of record 😄

**Comment by bbqsrc** [comment]
Move fast and don't break things, that's how I like to be.

**Comment by snorrees** [comment]
You might want to consider rebuilding https://github.com/divvun/ck-ospell to get the travis-build to report ok.

**Pull request merged**
